//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuodLib.WinForms.Drawing.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuodLib.WinForms.Drawing.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Furdomus_12x18_bold_ch {
            get {
                object obj = ResourceManager.GetObject("Furdomus_12x18_bold_ch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Furdomus_12x18_bold_ch1 {
            get {
                object obj = ResourceManager.GetObject("Furdomus_12x18_bold_ch1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Furdomus_12x18_bold_ch2 {
            get {
                object obj = ResourceManager.GetObject("Furdomus_12x18_bold_ch2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size=12,18
        ///NumHeight=14
        ///Padding=2
        ///
        ///A=0,0,10
        ///B=1,0,10
        ///C=2,0,10
        ///D=3,0,10
        ///E=4,0,10
        ///F=5,0,10
        ///G=6,0,10
        ///H=7,0,10
        ///I=8,0,8
        ///J=9,0,10
        ///K=10,0,11
        ///L=11,0,10
        ///M=12,0,12
        ///N=13,0,10
        ///O=14,0,12
        ///P=15,0,10
        ///Q=16,0,10
        ///R=17,0,10
        ///S=18,0,10
        ///T=19,0,8
        ///U=20,0,10
        ///V=21,0,12
        ///W=22,0,12
        ///X=23,0,12
        ///Y=24,0,12
        ///Z=25,0,12
        ///
        ///a=0,1,12
        ///b=1,1,10
        ///c=2,1,8
        ///d=3,1,12
        ///e=4,1,10
        ///f=5,1,10
        ///g=6,1,10
        ///h=7,1,10
        ///i=8,1,7
        ///j=9,1,9
        ///k=10,1,8
        ///l=11,1,9
        ///m=12,1,12
        ///n=13,1,10
        ///o=14,1,10
        ///p=15,1,10
        ///q=16,1,10
        ///r=17,1,9
        ///s=18,1,10
        ///t=19 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Furdomus_12x18_bold_df {
            get {
                return ResourceManager.GetString("Furdomus_12x18_bold_df", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Furdomus_6x9_ch {
            get {
                object obj = ResourceManager.GetObject("Furdomus_6x9_ch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Furdomus_6x9_ch1 {
            get {
                object obj = ResourceManager.GetObject("Furdomus_6x9_ch1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Furdomus_6x9_ch2 {
            get {
                object obj = ResourceManager.GetObject("Furdomus_6x9_ch2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size=6,9
        ///NumHeight=7
        ///
        ///A=0,0,5
        ///B=1,0,5
        ///C=2,0,5
        ///D=3,0,5
        ///E=4,0,5
        ///F=5,0,5
        ///G=6,0,5
        ///H=7,0,5
        ///I=8,0,4
        ///J=9,0,5
        ///K=10,0,5
        ///L=11,0,5
        ///M=12,0,6
        ///N=13,0,5
        ///O=14,0,5
        ///P=15,0,5
        ///Q=16,0,5
        ///R=17,0,5
        ///S=18,0,5
        ///T=19,0,4
        ///U=20,0,5
        ///V=21,0,6
        ///W=22,0,6
        ///X=23,0,6
        ///Y=24,0,6
        ///Z=25,0,6
        ///
        ///a=0,1,6
        ///b=1,1,5
        ///c=2,1,4
        ///d=3,1,6
        ///e=4,1,5
        ///f=5,1,5
        ///g=6,1,5
        ///h=7,1,5
        ///i=8,1,2
        ///j=9,1,5
        ///k=10,1,4
        ///l=11,1,5
        ///m=12,1,6
        ///n=13,1,5
        ///o=14,1,5
        ///p=15,1,5
        ///q=16,1,5
        ///r=17,1,5
        ///s=18,1,5
        ///t=19,1,5
        ///u=20,1,5
        ///v=21,1,6
        ///w=22,1,6
        ///x=23,1,4
        ///y=24, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Furdomus_6x9_df {
            get {
                return ResourceManager.GetString("Furdomus_6x9_df", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Furdomus_8x12_ch {
            get {
                object obj = ResourceManager.GetObject("Furdomus_8x12_ch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Furdomus_8x12_ch1 {
            get {
                object obj = ResourceManager.GetObject("Furdomus_8x12_ch1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Furdomus_8x12_ch2 {
            get {
                object obj = ResourceManager.GetObject("Furdomus_8x12_ch2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size=8,12
        ///NumHeight=9
        ///Padding=2
        ///
        ///A=0,0,7
        ///B=1,0,7
        ///C=2,0,7
        ///D=3,0,7
        ///E=4,0,7
        ///F=5,0,7
        ///G=6,0,7
        ///H=7,0,7
        ///I=8,0,6
        ///J=9,0,7
        ///K=10,0,7
        ///L=11,0,7
        ///M=12,0,8
        ///N=13,0,7
        ///O=14,0,7
        ///P=15,0,7
        ///Q=16,0,8
        ///R=17,0,7
        ///S=18,0,7
        ///T=19,0,6
        ///U=20,0,7
        ///V=21,0,8
        ///W=22,0,8
        ///X=23,0,8
        ///Y=24,0,8
        ///Z=25,0,8
        ///
        ///a=0,1,7
        ///b=1,1,7
        ///c=2,1,6
        ///d=3,1,8
        ///e=4,1,7
        ///f=5,1,7
        ///g=6,1,7
        ///h=7,1,7
        ///i=8,1,2
        ///j=9,1,7
        ///k=10,1,6
        ///l=11,1,7
        ///m=12,1,8
        ///n=13,1,7
        ///o=14,1,6
        ///p=15,1,7
        ///q=16,1,7
        ///r=17,1,6
        ///s=18,1,6
        ///t=19,1,7
        ///u=20,1,7
        ///v=21,1,8
        ///w=22,1,8
        ///x=2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Furdomus_8x12_df {
            get {
                return ResourceManager.GetString("Furdomus_8x12_df", resourceCulture);
            }
        }
    }
}
